@startuml
skinparam classAttributeIconSize 0
class DiceRoll {
+ diceNum : Int
+ RollDice(type: String): void
}

abstract class Item <<abstract>> {
+ {abstract} TypedActionResult<ItemStack> use(world: World, user: PlayerEntity, hand: Hand) <<abstract>>
}

class NegativeDice {
+ NegativeDice(settings: Settings) <<constructor>>
+ {abstract} TypedActionResult<ItemStack> use(world: World, user: PlayerEntity, hand: Hand)
}

class PositiveDice {
+ PositiveDice(settings: Settings) <<constructor>>
+ {abstract} TypedActionResult<ItemStack> use(world: World, user: PlayerEntity, hand: Hand)
}

class NeutralDice {
+ NegativeDice(settings: Settings) <<constructor>>
+ {abstract} TypedActionResult<ItemStack> use(world: World, user: PlayerEntity, hand: Hand)

}

class ModdedItems {
+ {field} {static} NEUTRALDICE: Item = registerItems("neutral_dice", new NeutralDice(new FabricItemSettings())) {readOnly}
+ {field} {static} NEGATIVEDICE: Item = registerItems("neutral_dice", new NeutralDice(new FabricItemSettings())) {readOnly}
+ {field} {static} POSITIVEDICE: Item = registerItems("neutral_dice", new NeutralDice(new FabricItemSettings())) {readOnly}
- {static} registerItems(name: String, item: Item): Item
- {static} addItemsToCreativeInv(entries: FabricItemGroupEntries): void
+ {static} InitRegisterItems(): void
}

interface ModInitializer <<interface>> {
+ onInitialize(): void
}

class DungeonsandMinecraft {
+ {field} {static} MOD_ID: String = "dungeons_and_minecraft"
+ {field} {static} LOGGER: Logger = LoggerFactory.getLogger(MOD_ID)
+ onInitialize(): void
}

interface DataGeneratorEntrypoint <<interface>> {
+ onInitializeDataGenerator(fabricDataGenerator: FabricDataGenerator): void
}

class DungeonsandMinecraftDataGenerator {
+ onInitializeDataGenerator(fabricDataGenerator: FabricDataGenerator): void
}

Item "0..*" <|-- "0..*" NegativeDice
Item "0..*     " <|-- "0..*" PositiveDice
Item "0..*" <|-- "0..*      " NeutralDice
Item "0..*" <--> " 0..*" ModdedItems

DiceRoll <-- Item

DungeonsandMinecraft "1  " ..|> "1  " ModInitializer

DungeonsandMinecraftDataGenerator "1  " ..|> "1  " DataGeneratorEntrypoint
@enduml