@startuml

state start <<start>>
state LeseEvent
state Interaktion
state GeneriereZufallsZahl
state EntscheideEreignis
state MarkiereBereich
state EntferneBloeke
state AndereEreignisse
state choice <<choice>>

start -right-> LeseEvent :onInitialize
LeseEvent --> Interaktion :Rechtsklick
Interaktion --> GeneriereZufallsZahl :TypedActionResult<ItemStack>use(world, user, hand);
GeneriereZufallsZahl --> EntscheideEreignis :EntscheideEreignis(pZufallsZahl, ServerWelt);
EntscheideEreignis --> choice
choice --> MarkiereBereich : [ZufallsZahl == 2]
choice --> AndereEreignisse :[ZufallsZahl != 2]
MarkiereBereich --> EntferneBloeke
EntferneBloeke -left-> LeseEvent
@enduml